var restrictions = [
    'One Arm',
    'One Leg',
    'On Knees',
    'On Back',
    'On Elbows',
    'On Stomach',
    'Standing',
    'Direction Change',
    'Travel Forward/Back',
    'Travel Sideways',
    'Level Change',
    'Threading',
    'Atomic Style',
    'With Stab'
]

var textures = [
    'Waves',
    'Fire',
    'Floating',
    'Sinking',
    'Wide',
    'Narrow',
    'Slippery',
    'Jagged',
    'Elevator',
    'Boomerang',
    'Martial Arts',
    'Broken Record',
    'Leaning Tower',
    'Gunshot',
    'Ping Pong',
    'Beyblade',
    'Orbit',
    'Balloon',
    'Wings',
    'Noodle',
    'Snake',
    'Monkey',
    'Molasses',
    "Paintbrush"
]

var shapes = [
    'Line',
    'Triangle',
    'Square',
    'Circle',
    'Figure 8',
    'Flower',
    'Letter V',
    'Letter C',
    'Letter L',
    'Letter S',
    'Letter X',
    'Letter Z',
    'Star',
    'Knot',
    'Pendulum'
]

var moves = [
    '1 Step',
    '2 Step',
    '3 Step',
    '4 Step',
    '6 Step',
    '12 Step',
    'CC',
    'Backrock CC',
    'Zulu',
    'Monkey Swing',
    'Russian Step',
    'Hook',
    'Sweep',
    'Pretzel',
    'Figure 4',
    'Kickout',
    'One Leg Kickout',
    'Baby Freeze',
    'Turtle Freeze',
    'Chair Freeze',
    'Shoulder Freeze',
    'Side Freeze',
    'Nike',
    'Headstand',
    'Knee Drop',
    'Corkscrew',
    'Hip Twist',
    'Side Step',
    'Cross Step',
    'Shuffle',
    'Reverse 1 Step'
]

const params = [restrictions, textures, shapes, moves]
